### ISSUE TITLE
Bot not Betting / Getting match info

### ISSUE THREAD

**Issue by ervueo** [FranciscoAT/saltyboy#28]
Here is the error info from Edge:
===
Current Match from server is out of date Mhp ecoco Thin yusuke [object Object]

Context

https://www.saltybet.com/

Stack Trace

content_script.js:1 (anonymous function)
===

There is a large amount of code that follows, but it includes this: 
(e=>{console.error("Something went wrong getting current match from server.",e)

**Comment by FranciscoAT** [comment]
Possible the server just failed. I'll kick it later tonight, will be down for a few hours until I can fix.

**Comment by ervueo** [comment]
Thanks. Looking at https://salty-boy.com/current-match it has a number of matches in there, some dating back to 2021. Just something I noticed too.

**Comment by FranciscoAT** [comment]
Looks like the scraping bot failed unexpectedly. No root cause as to why. But it had a pretty good up-time since I last rebooted it so I'll leave it as is.

> Thanks. Looking at https://salty-boy.com/current-match it has a number of matches in there, some dating back to 2021. Just something I noticed too.

Correct, `/current-match` is effectively a quick easy endpoint to list the current two fighters in a single API request. It contains a historical listing of each fighters matches so as to let the bot, Chrome extension, to determine odds based off of your settings + bet strategy.
