### ISSUE TITLE
The bot keeps inputting $1

### ISSUE THREAD

**Issue by WormyDragon** [FranciscoAT/saltyboy#76]
Hello, I am on Oprea GX and it seems the bot keeps putting in $1. Please help

**Comment by FranciscoAT** [comment]
Hi there! Looks like the bot that scraped the matches died around mid-day yesterday UTC. Typically the fix just involves me restarting the bot on the server. If this ever happens again feel free to leave a comment informing the bot died on this issue here: https://github.com/FranciscoAT/saltyboy/issues/62, I'll usually get to it as soon as I can. 

Hopefully, things are working for you now! Feel free to leave another issue if something still isn't working as expected. :)
